[RN0.66] 6/n: Various Android updates
Summary:
Various changes that apply to Android config files for the React Native upgrade.

Note that there are three changes here from React Native 0.67:

- Fixing typo in code comment in `native/android/app/build.gradle`
- Fixing typo in code comment in `native/android/gradle.properties`
- `excludeGroup "com.facebook.react"` for `mavenCentral` in `native/android/build.gradle`

Also note that the changes to the NDK version here will necessitate that every developer installs the new NDK version here. Otherwise you will see this error when trying to run any Gradle build:

```
org.gradle.api.InvalidUserDataException: NDK not configured. Download it with SDK manager. Preferred NDK version is '21.4.7075529'.
```

Also note that I was unable to remove the `jcenter` dependency because of [this](https://github.com/react-native-video/react-native-video/issues/2454) `react-native-video` issue.

Test Plan: Built and ran the whole stack on iOS and Android across various architectures

Reviewers: palys-swm, atul

Subscribers: Adrian, karol-bisztyga

Differential Revision: https://phabricator.ashoat.com/D2985