[native] replace `uint` with `unsigned int`
Summary: Emscripten compiler (for some reason) does not recognize `uint`, and cause: ` error: use of undeclared identifier 'uint'; did you mean 'int'?`

Depends on D8488

Test Plan: N/A

Reviewers: michal, tomek, jon, atul