[services] Tunnelbroker - Fix `DatabaseManagerTest.cpp` build error on non-closed brackets
Summary:
Fix `DatabaseManagerTest.cpp` build error on non-closed brackets which was discovered during the new builds:

```
DatabaseManagerTest.cpp:185:80: error: expected ')'
[build]       "mobile:EMQNoQ7b2ueEmQ4QsevRWlXxFCNt055y20T1PHdoYAQRt0S6TLzZWNM6XSvdWqxm";
```

Linear task: [[ https://linear.app/comm/issue/ENG-1067/fix-tunnelbroker-databasemanagertestcpp-build-error | ENG-1067 ]]

Test Plan: Run `yarn test-tunnelbroker-service` to build and run the tests.

Reviewers: karol-bisztyga, palys-swm, varun, ashoat

Reviewed By: ashoat

Subscribers: ashoat, palys-swm, Adrian, atul, karol-bisztyga, yayabosh

Differential Revision: https://phabricator.ashoat.com/D3881