[identity] ensure identity reqwest crate has rustls-tls
Summary:
We disabled default features for reqwest when we upgraded to cargo workspaces. This caused reqwest to compile without defalut TLS capability, leading to
https://linear.app/comm/issue/ENG-8611/identity-user-search-not-working-on-staging

This diff adds rustls-tls as a feature to the reqwest crate

Test Plan:
Ran `reqwest` search query request to opensearch domain with no default features, causing

```
Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("opensearch-domain")), port: None, path: "/users/_search/", query: None, fragment: None }, source: hyper_util::client::legacy::Error(Connect, "invalid URL, scheme is not http") }
```

On adding back rustls-tls, this resolved the issue and returned search results. Tested on upgraded identity image and search results on the iOS simulator app was restored

Reviewers: bartek, varun

Reviewed By: varun

Subscribers: ashoat, tomek

Differential Revision: https://phab.comm.dev/D12621