[native] Fix JNI exception messages on Android
Summary:

Fix [[ https://linear.app/comm/issue/ENG-11070/investigate-unable-to-get-exception-message | ENG-11070 ]].

Depends on D15190

Test Plan:

Confirmed that a proper error message with stacktrace is now displayed, example:
```
java.lang.RuntimeException: Java exception: app.comm.android.aescrypto.DecryptionFailedException: AES Decryption failed
	at app.comm.android.aescrypto.AESCryptoModuleCompat$Companion.decrypt(AESCryptoModule.kt:174)
	at app.comm.android.aescrypto.AESCryptoModuleCompat.decrypt(Unknown Source:2)
	at com.facebook.jni.ThreadScopeSupport.runStdFunctionImpl(Native Method)
	at com.facebook.jni.ThreadScopeSupport.runStdFunction(ThreadScopeSupport.java:32)

	at com.facebook.jni.ThreadScopeSupport.runStdFunctionImpl(Native Method)
	at com.facebook.jni.ThreadScopeSupport.runStdFunction(ThreadScopeSupport.java:32)
```

Reviewers: angelika

Subscribers: