[web] Fix error when opening sidebar that user is not a member of
Summary:
In sidebarInfos we store only sidebars that user is a member of and that are visible, but inline we show all sidebars.
Steps to reproduce error:
1. Create sidebar with only one member of parent thread
2. As not a member of a sidebar, press inline sidebar (requires next diff arc patched) and see invariant

Test Plan: Verify that opening inline sidebars is not causing invariant, and that sidebar is set as active in chat thread list

Reviewers: ashoat, palys-swm

Reviewed By: ashoat

Subscribers: zrebcu411, Adrian, atul, subnub, karol-bisztyga

Differential Revision: https://phabricator.ashoat.com/D680