[services] add back default features to reqwest in cargo workspaces
Summary:
We disabled default features for reqwest when we upgraded to cargo workspaces. This caused reqwest to compile without defalut TLS capability, leading to
https://linear.app/comm/issue/ENG-8611/identity-user-search-not-working-on-staging

Test Plan:
Ran `reqwest` search query request to opensearch domain with no default features, causing

```
Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("opensearch-domain")), port: None, path: "/users/_search/", query: None, fragment: None }, source: hyper_util::client::legacy::Error(Connect, "invalid URL, scheme is not http") }
```

On adding back default features, this resolved the issue and returned search results

Reviewers:
bartek,
varun

Subscribers: