[native] Delay autoFocus in RelationshipUpdateModal
Summary:
I noticed the following native exception being thrown in the Android simulator whenever I open `RelationshipUpdateModal`:

```
com.facebook.react.bridge.JSApplicationCausedNativeException: Illegal node ID set as an input for Animated.Add node
```

It's hard to debug native exceptions, so I wasn't able to get to the bottom of why this is occurring. However, I found that removing the `autoFocus` fixed the issue. I guess we need to wait a little bit before focusing a `TextInput` that appears during an animated transition.

Test Plan: Be able to open `RelationshipUpdateModal` on Android emulator without crashing

Reviewers: palys-swm

Reviewed By: palys-swm

Subscribers: KatPo, zrebcu411, Adrian

Differential Revision: https://phabricator.ashoat.com/D409